# Generated by Django 4.1.7 on 2023-03-25 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('num', models.CharField(max_length=40)),
                ('response', models.CharField(max_length=40)),
                ('count', models.CharField(max_length=5)),
                ('num_kab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invent.kab')),
            ],
        ),
    ]
