# Generated by Django 4.1.7 on 2023-04-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_alter_inventar_options_alter_kab_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kab',
            name='num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
